### PR TITLE
Enable release plugin for ivy plugin with optional dependency

### PR DESCRIPTION
**Pull request by fbuehlmann**
**Add release functionality to 3rd party plugins without code dependency**
There are two plugins that could also benefit from release funtionality:
- Ivy Plugin

I integrated the functionality to these plguins without getting dependency to the plugin code.

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
I'm not sure how this change is supposed to work. Needs clarification

**Comment by fbuehlmann** [comment]
There was one commit missing in my request. Therefore I reimplemented it right now.

**Comment by oleg-nenashev** [comment]
Well, it messes up the code even more :(
Could you get rid of unrelated formatting changes?

**Comment by fbuehlmann** [comment]
Now only the changed code is in the commits. Sorry for that.

**Comment by oleg-nenashev** [comment]
Great, now it is much more reviewable :)

Generally, I would vouch for adding *optional* dependencies to these plugins (with referencing compatible versions) and maybe writing some tests. It's not really required, because ideally this plugin should provide an extension point, which would allow other plugins to declare the compatibility. So I consider it only as a temporary fix (CC @jenkinsci/code-reviewers).

Maybe it's also better to use full class names since generic class names "GroupJobProject" may potentially overlap with other OSS or internal plugins.

**Comment by oleg-nenashev** [comment]
@fbuehlmann gentle ping. I could merge it as-is, but I would to get clarification regarding usage of not-fully-qualified names

**Comment by fbuehlmann** [comment]
I would refactor to optional dependencies. This sounds the best to me.

**Comment by oleg-nenashev** [comment]
LGTM

**Pull request merged**
