### PR TITLE
SECURITY-1928 Fix stored xss

### PR DESCRIPTION
**Pull request by timja**
(Will ship anyway since fix is so minor but FYI)

### CODE REVIEW

**Comment by Smasherr** [comment]
Hey @timja, thanks for this fix, but do you have any clue why this plugin is still marked as vulnerable?

**Comment by timja** [comment]
Cc @daniel-beck

**Comment by daniel-beck** [comment]
Because nobody bothered to let the security team know (personal account as reviewer doesn't count) 😉 

https://www.jenkins.io/security/plugins/#followup explains followup, I put it on my list for later, or someone else can file the PR.

**Comment by Smasherr** [comment]
I could open a PR but I am confused about a widely used pattern in https://github.com/jenkins-infra/update-center2/blob/master/resources/warnings.json Maybe you could explain to me what is the use of the capture group `(|[.-].*)` (or `(|[.-].+)`)? It matches either of two alternatives
- `null`
- dot or dash and an arbitrary number (at least one) of any characters

Since `null` is the first alternative and it can be always matched, the capture is always `null` and the second alternative is never used. Am I missing something here?

**Comment by daniel-beck** [comment]
@Smasherr 

> Since `null` is the first alternative and it can be always matched, the capture is always `null` and the second alternative is never used. Am I missing something here?

Not quite, as this doesn't match a substring (`Matcher#find` or similar), but the entire version number (`Pattern#match`). So `1[.]0` would _not_ match `1.0.1`, but `(1[.]0)(|[.-].+)` does, in addition to `1.0` and `1.0.0`. Which allows me to do things like the first part of https://github.com/jenkins-infra/update-center2/blob/1690b80d6a92489c1be9ba51105c47ba4f3e5d9d/resources/warnings.json#L9778 to express "anything lower than major version 8".

This plugin nicely illustrates why this is useful, the pattern should probably be `(1|2[.][0-9]|2[.]10)(|[.-].+)` or similar.

As to why I don't write `([.-].+)?` instead, as I've been asked before: Personal preference (and now, consistency).

**Comment by Smasherr** [comment]
Okay, I've got your point, it makes sense now to me. Thank you for the explanations.

**Pull request merged**
