### PR TITLE
[JENKINS-43490] Add wait parameter to release function

### PR DESCRIPTION
**Pull request by mustafau**
Adds ability to **not** wait until downstream job finishes.

### CODE REVIEW

**Comment by mustafau** [comment]
Ping @oleg-nenashev

**Comment by oleg-nenashev** [comment]
Sorry, it appears I was not watching this repo. Thanks for the ping

**Comment by mustafau** [comment]
I added 2 new commits to address your request.

**Comment by mustafau** [comment]
Ping @oleg-nenashev

**Comment by oleg-nenashev** [comment]
Sorry, missed the ping. Will try to review in a couple of days

**Comment by oleg-nenashev** [comment]
> AFAICT it is some kind of specialized clone of the build step, which sounds like a bad idea.

Syntax sugar, no? Actually there is also some extra metadata injected, so I am fine with the current design.

**Comment by oleg-nenashev** [comment]
@mustafau any plans to finalize it?

**Comment by mustafau** [comment]
@oleg-nenashev I didn't understand what needs to be done. Pipeline build step plugin only uses `wait` parameter inside `BuildTriggerStepExecution.start` method. So I did the same.

**Comment by mustafau** [comment]
@oleg-nenashev @jglick I have migrated away from the Release Plugin. I am not going to work on this PR anymore.

**Pull request closed without merging**
